### ISSUE TITLE
Refactorizar el main.dart

### ISSUE THREAD

**Issue by Rodrigoberes24** [Rodrigoberes24/FrecciaVeloce#2]
1-Crear nuevo branch a partir del master llamado feature/xx (xx se reemplaza por el numero de esta issue, en este caso es 2, seria feature/2)
2-Escribir en la terminal git checkout feature/2 en vs code, nos vamos a mover al branch recientemente creado
3- Eliminar comentarios dentro del main.dart
4-Eliminar [parametro](https://github.com/Rodrigoberes24/FrecciaVeloce/blob/master/lib/main.dart#L27) que pasamos de myApp (Eliminar solo title: 'Flutter Demo Home Page') a [HomePage](https://github.com/Rodrigoberes24/FrecciaVeloce/blob/master/lib/main.dart#L33) (En my HomePage solo borrar required this.title)
5-Eliminar Widgets de texto, 
6-eliminar el [FloatingactionButton](https://github.com/Rodrigoberes24/FrecciaVeloce/blob/master/lib/main.dart#L108) que nos distribuye el Scaffold, 
7-eliminar [metodo](https://github.com/Rodrigoberes24/FrecciaVeloce/blob/master/lib/main.dart#L53) void de contador,
8-eliminar variables que no se usan mas, [int](https://github.com/Rodrigoberes24/FrecciaVeloce/blob/master/lib/main.dart#L51) y [String](https://github.com/Rodrigoberes24/FrecciaVeloce/blob/master/lib/main.dart#L44)

**Comment by foberti69** [comment]
`import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, }) : super(key: key);

 

  

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
 

  

  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      appBar: AppBar(
       
        title: Text(""),
      ),
      body: Center(
       
        child: Column(
         
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            
            
          ],
        ),
      ),
     
    );
  }
}
`

**Comment by foberti69** [comment]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, }) : super(key: key);

 

  

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
 

  

  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      appBar: AppBar(
       
        title: Text(""),
      ),
      body: Center(
       
        child: Column(
         
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            
            
          ],
        ),
      ),
     
    );
  }
}


```
